title: Domain Expiration Dates
description: A list of domain expiration dates and remaining time.
baseurl: "" # the subpath of your site, e.g., /blog
url: "Q.TD" # the base hostname & protocol for your site, e.g., http://example.com

# Build settings
markdown: kramdown
theme: minima

# Custom variables
domains:
  - domain: AGI.AO
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-17"
  - domain: SOS.AO
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-16"
  - domain: SOSO.AO
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-16"
  - domain: UFO.AO
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-17"
  - domain: VPN.AO
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-15"
  - domain: WPS.AO
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-15"
  - domain: ISO.AO
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-17"
# (Continued in the next message...)
# (Continuing from the previous message...)
  - domain: 4.KE
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-02-15"
  - domain: 98.KE
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-18"
  - domain: AGI.KE
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-18"
  - domain: GPT.KE
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-16"
  - domain: KB.KE
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-17"
  - domain: KD.KE
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-17"
  - domain: KEE.KE
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-17"
# (Continued in the next message...)
# (Continuing from the previous message...)
  - domain: KEY.KE
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-16"
  - domain: KKK.KE
    description: "@Give me five✋♣kenyawebexperts. $22♣"
    registration_date: "2024-04-16"
  - domain: Q.TD
    description: "@Give me five✋♣afriregister. $22♣"
    registration_date: "2022-09-03"
  - domain: GPT.TD
    description: "@Give me five✋♣afriregister. $22♣"
    registration_date: "2023-04-10"
  - domain: DT.TD
    description: "@Give me five✋♣afriregister. $22♣"
    registration_date: "2022-07-03"
  - domain: 9.SRL
    description: "@Give me five✋♣webhost. $22♣"
    registration_date: "2022-04-21"
  - domain: NB.AL
    description: "@Give me five✋♣webhost. $22♣"
    registration_date: "2024-04-08"
