domain: Q.TD
title: Young
title_ext: King

contacts:
  - icon: "fa fa-envelope"
    url: "8327811@qq.com"
    text: 8327811@qq.com
  - icon: "fa fa-qq"
    text: 18677798881
  # - icon: "fa fa-wechat"
  #   text: wechat-username

domains:
  - domain: 4.KE
    description: "@Give me five✋"
    description: "kenyawebexperts" description: "$29.9"
  - domain: 9.SRL
    description: "@Give me five✋"
    description: "porkbun" description: "$28.89"
  - domain: Q.TD
    description: "@Give me five✋"
    description: "afriregister" description: "22.26€"
  - domain: DT.TD
    description: "@Give me five✋"
    description: "afriregister" description: "22.26€"
  - domain: GPT.TD
    description: "@Give me five✋"
    description: "afriregister" description: "22.26€"
  - domain: WPS.AO
    description: "@Give me five✋"
    description: "angoweb" description: "$22.35"
  - domain: VPN.AO
    description: "@Give me five✋"
    description: "angoweb" description: "$22.35"
  - domain: GPT.AO
    description: "@Give me five✋"
    description: "angoweb" description: "$22.35"
  - domain: NB.AL
    description: "@Give me five✋"
    description: "innovahost" description: "10..99€"
