domain: Q.TD
title: Young
title_ext: King

contacts:
  - icon: "fa fa-envelope"
    # url: "8327811@qq.com"
    # text: 8327811@qq.com
  - icon: "fa fa-qq"
    text: 18677798881
  # - icon: "fa fa-wechat"
  #   text: wechat-username
  
domains:
  - domain: AGI.AO
    description: "概念: 通用大模型/AI的最终归属！"
    price: 22.35
    registration_date: "2024-04-17"
  - domain: SOS.AO
    description: "概念: 求救、求助！"
    price: 22.35 
    registration_date: "2024-04-16"
  - domain: SOSO.AO
    description: "概念: 搜搜、适合搭建引擎网站！"
    price: 22.35 
    registration_date: "2024-04-16"
  - domain: UFO.AO
    description: "概念: 未知、外星人概念！"
    price: 22.35 
    registration_date: "2024-04-17"
  - domain: VPN.AO
    description: "概念: 科学上网你懂的！"
    price: 22.35 
    registration_date: "2024-04-15"
  - domain: WPS.AO
    description: "概念: 文字处理系统/适合文字处理工具的集成网站！"
    price: 22.35 
    registration_date: "2024-04-15"
  - domain: ISO.AO
    description: "概念: 行业标准！"
    price: 22.35
    registration_date: "2024-04-17"
  - domain: 4.KE
    description: "概念: 4K分辨率!"
    price: 22
    registration_date: "2024-02-15"
  - domain: 98.KE
    description: "概念: 吃鸡都知道!"
    price: 22
    registration_date: "2024-04-18"
  - domain: AGI.KE
    description: "概念: 通用大模型/AI的最终归属！"
    price: 22 
    registration_date: "2024-04-18"
  - domain: GPT.KE
    description: "概念: 最火的AI模型没有之一！"
    price: 22 
    registration_date: "2024-04-16"
  - domain: KB.KE
    description: "概念: “科比”！"
    price: 22 
    registration_date: "2024-04-17"
  - domain: KD.KE
    description: "概念: 杜兰特/也是AB.AC的小递增!"
    price: 22
    registration_date: "2024-04-17"
  - domain: KEE.KE
    description: "概念: 完美ABB.AB!!"
    price: 22 
    registration_date: "2024-04-17"
  - domain: KEY.KE
    description: "概念: 钥匙/密钥 适合中转网站搭建！"
    price: 22 
    registration_date: "2024-04-16"
  - domain: KKK.KE
    description: "概念: AAA.AB的概念顺口溜！"
    price: 22 
    registration_date: "2024-04-16"
  - domain: 9.SRL
    description: "概念: 共享资源概念，简称就共享！"
    price: 22.89 
    registration_date: "2022-04-21"
  - domain: Q.TD 
    description: "概念: TD技术部门,有问题Q.TD！"
    price: 22.26
    registration_date: "2022-09-03"
  - domain: DT.TD
    description: "概念: 完美的镜像米！"
    price: 22.26 
    registration_date: "2022-07-03"
  - domain: GPT.TD
    description: " 概念: 最火的AI模型没有之一!"
    price: 22.26
    registration_date: "2023-04-10"
  - domain: NB.AL
    description: "概念: 牛逼的网站!"
    price: 10.99 
    registration_date: "2024-04-08"
