domain: Q.TD
title: Young
title_ext: King

contacts:
  - icon: "fa fa-envelope"
    url: "8327811@qq.com"
    text: 8327811@qq.com
  - icon: "fa fa-qq"
    text: 18677798881
  # - icon: "fa fa-wechat"
  #   text: wechat-username

domains:
  - domain: 4.KE
    description: "@Give me five✋"
  - domain: 9.SRL
    description: "@Give me five✋"
  - domain: Q.TD
    description: "@Give me five✋"
  - domain: DT.TD
    description: "@Give me five✋"
  - domain: GPT.TD
    description: "@Give me five✋"
  - domain: WPS.AO
    description: "@Give me five✋"
  - domain: VPN.AO
    description: "@Give me five✋"
  - domain: NB.AL
    description: "@Give me five✋"
